@isTest
public class ETT_MiscReceiptTest {
    static testmethod void ETT_MiscReceipt(){
        ETT_MiscReceipt misc = new ETT_MiscReceipt();
        
        ETT_MiscReceipt.Lotnumber_lines_element obj1 = new ETT_MiscReceipt.Lotnumber_lines_element();
        ETT_MiscReceipt.process_element obj2 = new ETT_MiscReceipt.process_element();
        ETT_MiscReceipt.Data_Header_type obj3 = new ETT_MiscReceipt.Data_Header_type();
        ETT_MiscReceipt.OutputParameters_element obj4 = new ETT_MiscReceipt.OutputParameters_element();
        ETT_MiscReceipt.Serialnumber_lines_element obj5 = new ETT_MiscReceipt.Serialnumber_lines_element();
        ETT_MiscReceipt.MessageHeader obj6 = new ETT_MiscReceipt.MessageHeader();
        ETT_MiscReceipt.MessageXml obj7 = new ETT_MiscReceipt.MessageXml();
        ETT_MiscReceipt.Data_Lines_type obj8 = new ETT_MiscReceipt.Data_Lines_type();
    }

}